require_relative "config/environment"
require "sinatra/activerecord/rake"

desc "Runs a Pry console"
task :console do
  # This line turns on logging of the SQL generated by Active Record
  ActiveRecord::Base.logger = Logger.new($stdout)

  # Open a Pry session
  Pry.start
end

desc "Start the server"
task :server do
  # rerun allows auto-reloading of server when files are updated
  # -b runs in the background (include it or binding.pry won't work)
  exec "bundle exec rerun -b 'rackup config.ru'"
end
